notifications:
  email: false

language: cpp

# if pull request: always build
# if push: only build for master branch
if: (type != push) OR (type = push AND branch = master)

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - libasound2-dev
            - libxcursor-dev
            - libxinerama-dev
            - libxrandr-dev
            - webkit2gtk-4.0
      env:
        - GENERATOR="Unix Makefiles"
        - app=$TRAVIS_BUILD_DIR/build/MasterEars
        - zipcmd="zip -r $TRAVIS_BUILD_DIR/Bin/${TRAVIS_OS_NAME}_app.zip $TRAVIS_BUILD_DIR/Bin/bins"
    
    - os: osx
      env:
        - GENERATOR=Xcode
        - app=$TRAVIS_BUILD_DIR/build/Release/MasterEars.app
        - zipcmd="zip -r $TRAVIS_BUILD_DIR/Bin/${TRAVIS_OS_NAME}_app.zip $TRAVIS_BUILD_DIR/Bin/bins"
      osx_image: xcode9.4

    - os: windows
      env:
        - GENERATOR="Visual Studio 15 2017 Win64"
        - app=$TRAVIS_BUILD_DIR/build/Release/App/MasterEars.exe
        - zipcmd="powershell Compress-Archive $TRAVIS_BUILD_DIR/Bin/bins/ $TRAVIS_BUILD_DIR/Bin/${TRAVIS_OS_NAME}_app.zip"

install:
  - echo ${GENERATOR}
  - cmake --version

  - git clone --branch=5.4.7 --depth=1 --single-branch
    -- https://github.com/jatinchowdhury18/JUCE.git ../JUCE

  - git clone https://github.com/McMartin/FRUT.git ../FRUT

  # configure and install FRUT
  - cd ../FRUT/
  - mkdir build && cd build/
  - cmake .. -DCMAKE_INSTALL_PREFIX=../prefix -DJUCE_ROOT=../../JUCE
  - cmake --build . --target install

script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build && cd build/
  - cmake .. -G "${GENERATOR}"
  - cmake --build . --config Release

after_success:
  - |
    cd $TRAVIS_BUILD_DIR

    echo "Setting up Git..."
    git config --global user.email "travis@travis-ci.org"
    git config --global user.name "Travis CI"
    git checkout -b Builds
    git rebase origin/Builds

    echo "Copying files..."
    mkdir $TRAVIS_BUILD_DIR/Bin/bins
    cp -R $app $TRAVIS_BUILD_DIR/Bin/bins/
    rm ${TRAVIS_OS_NAME}_app.zip
    $zipcmd
    rm -R $TRAVIS_BUILD_DIR/Bin/bins

    echo "Committing files..."
    git add Bin
    git commit -m "Travis build - $TRAVIS_BUILD_NUMBER, $TRAVIS_OS_NAME"

    echo "Pushing to branch..."
    git push https://${GH_TOKEN}@github.com/jatinchowdhury18/MasterEars.git

env:
  global:
    secure: XwNTCMb1qb7AHGEq8Pk1L0kc0zReC0OBulKaadNRPoPm3nOd/AAcvsMrw15QEsWADr+kieiiCjCnZTqH0XxpGzGzLjryuBdNEu70z/yocJQOP+osXMA26CZz23dURhIBprVbkME5uy1rMLUyFBw7WUCFfF0iFlJfYI5o1m+2t1fL34TJ8GRbrpJGax5O1OpAA8GuIvz8mVUwV6W/cRbHL/dCUbP9yFW6BUapE6bas4xkH5GZxb28pZVXGTl0NxvE8Lce4r66KD2SV/Hcg/ZOX6BD7lprkn+MEZfsWz0Mfq+HXUTE13tTwC2wTe/jaR7AoJArf2irgT40saj42hTWNkXY8LiEAu1dS5WAbx1xvEdUxOU1ikU9nptPUOYQQoXvfCZu41ICbbrQqtzUJixhTDd34doXadUjk7O3Au5qvgauncQ/jn0l7wGpuE/nPblB+6RzKKQAAZoqr1tG/xTUymkCAp4/MzBOnl1mtIDo2oT1UJR6AVDxkEyYOOECH2gdPM1rGmvUgzUMeVTinu/3+kwCDHZmEYuLUQ3eGJELSVL3//nMXmTVBs17rqEkfvM/ZJAPviURzUlJrRDXnsWWDKEhqsa6Q85NJqH06faDlqSw1z7WvMcQgPfMYQLMZ6pzeEi2Aetv4nUTr7gUcv7waGLTNV9ZcaN6NkAcoZhQGSw=
